export const SHOW_MODAL = 'SHOW_MODAL';
export const HANDLE_OK = 'HANDLE_OK';
export const HANDLE_CANCEL = 'HANDLE_CANCEL';
export const HANDLE_DELETE = 'HANDLE_DELETE';
export const SET_NEW_USER_NAME = 'SET_NEW_USER_NAME';
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
